### PR TITLE
Use rpmExpandMacros on rpm v4.14+

### LINKED ISSUE #6: RPM[] fails on v4.14+
The `expandMacros` method was deprecated and replaced by `rpmExpandMacros` causing
```
RPMRPMTests#test_macro_read:
NoMethodError: undefined method `expandMacros' for module RPM::C
    lib/rpm.rb:47:in `[]'
    test/test_rpm.rb:28:in `test_macro_read'
```

### PR DESCRIPTION
**Pull request by agrare**
This fixes `RPM["_usr"]` from throwing an exception about `expandMacros`  not being defined.

Fixes https://github.com/ManageIQ/ruby-rpm-ffi2/issues/6

### CODE REVIEW

File: lib/rpm.rb [hunk 1]
```diff
@@ -41,11 +41,19 @@ def self.transaction(root = '/')
...
-    ret = RPM::C.expandMacros(nil, nil, buffer, 1024)
-    buffer.read_string
+    if C::rpm_version_code >= ((4 << 16) + (14 << 8) + (0 << 0))
+      obuf = ::FFI::MemoryPointer.new(:pointer)
+      sbuf = FFI::MemoryPointer.from_string("%{#{name}}")
+      ret = RPM::C.rpmExpandMacros(nil, sbuf, obuf, 0)
+      val = obuf.get_pointer(0)
+      val.read_string
+    else
+      val = ''
```
Comment (Fryguy) [inline lib/rpm.rb]: This val is not needed (Removed in #11)

Comment (agrare) [reply lib/rpm.rb]: Yes I still need to rebase this on your changes, done

File: lib/rpm.rb [hunk 2]
```diff
@@ -41,10 +41,22 @@ def self.transaction(root = '/')
   # @param [String] name Name of the macro
   # @return [String] value of macro +name+
   def self.[](name)
-    buffer = ::FFI::MemoryPointer.new(:pointer, 1024)
-    buffer.write_string("%{#{name}}")
-    ret = RPM::C.expandMacros(nil, nil, buffer, 1024)
-    buffer.read_string
+    if C::rpm_version_code >= ((4 << 16) + (14 << 8) + (0 << 0))
+      obuf = ::FFI::MemoryPointer.new(:pointer)
```
Comment (Fryguy) [inline lib/rpm.rb:45]: Do we need a max size on this? Or will it auto-realloc?

Comment (agrare) [reply lib/rpm.rb:45]: This is a `char ** ` and the memory is malloc'd by the `rpmExpandMacros` method.  I do think I need to free it after reading the string though just wanted to get the tests passing first.

File: lib/rpm.rb [hunk 3]
```diff
@@ -41,10 +41,22 @@ def self.transaction(root = '/')
...
+      sbuf = FFI::MemoryPointer.from_string("%{#{name}}")
+      ret = RPM::C.rpmExpandMacros(nil, sbuf, obuf, 0)
+      return if ret < 0
```
Comment (Fryguy) [inline lib/rpm.rb]: Should we just return or should we raise an exception?  From a caller perspective, this method is called like Rpm['foo'] so I think the caller expects it to expand...if it doesn't it will return nil, which feels wrong?

File: lib/rpm.rb (hunk 2 above)
Comment (Fryguy) [reply lib/rpm.rb:45]: Love me a good `char**` (or a `char***` I wrote once 🤣 )

File: lib/rpm.rb (hunk 3 above)
Comment (agrare) [reply lib/rpm.rb]: Yeah that's true I wonder if the return value has any pre-defined error codes that can help raise a useful exception

Comment (Fryguy) [reply lib/rpm.rb]: I'm ok with merging as is to get things green, and we can research it more later - it's up to you

Comment (agrare) [reply lib/rpm.rb]: I'll just raise a normal RuntimeError for now
